site_name: coveragespace
site_description: Command-line client for The Coverage Space.
site_author: Jace Browning
repo_url: https://github.com/jacebrowning/coverage-space-cli
# google_analytics: ['XX-XXXXXXXX-XX', 'jacebrowning.github.io/coverage-space-cli']

theme: mkdocs

pages:
- Home: index.md
- About:
  - 'Release Notes': about/changes.md
  - Contributing: about/contributing.md
  - License: about/license.md
